plugins {
    id 'com.android.application'
}

android {
    namespace 'es.odoovps.printbridge'
    compileSdk 34

    defaultConfig {
        applicationId "es.odoovps.printbridge"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "0.1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'com.sunmi:printerlibrary:1.0.24'
}
